def okr(a):
    for _ in range(360):
        turtle.forward(a)
        turtle.right(1)
def hlf(a):
    for i in range(180):
        turtle.forward(a)
        turtle.right(1)


import turtle
turtle.tracer(2)
turtle.penup()
turtle.left(90)
turtle.forward(200)
turtle.right(90)
turtle.pendown()
turtle.begin_fill()
okr(3)
turtle.color("yellow")
turtle.end_fill()
turtle.penup()
turtle.color("black")
turtle.right(90)
turtle.forward(50)
turtle.left(90)
turtle.backward(65)
turtle.pendown()
turtle.begin_fill()
okr(0.5)
turtle.color("blue")
turtle.end_fill()
turtle.color("black")
turtle.penup()
turtle.forward(130)
turtle.pendown()
turtle.begin_fill()
okr(0.5)
turtle.color("blue")
turtle.end_fill()
turtle.color("black")
turtle.penup()
turtle.backward(65)
turtle.right(90)
turtle.forward(100)
turtle.pendown()
turtle.width(10)
turtle.forward(50)
turtle.penup()
turtle.forward(30)
turtle.left(90)
turtle.forward(104)
turtle.right(90)
turtle.pendown()
turtle.color("red")
hlf(1.8)
turtle.update()
